### ISSUE TITLE
Section 2.2 - Precautionary statements with more than one number

### ISSUE THREAD

**Issue by EpicKris** [EpicKris/sdscom-xsl#4]
Section: 2.2

Precautionary statements with more than one number look like `P303P361P353` but should be connected with a plus sign, like `P303+P361+P353`.

**Comment by EpicKris** [comment]
@dirk-qualisys I've updated this, but shouldn't the section 2.2 node `HazardLabelling/ClpLabellingInfo/ClpPrecautionaryStatement/MergePhrase` be used for the `+` delimiter?

**Comment by dirk-qualisys** [comment]
No marge phrase here - the P phrase code is taken from the phrase codes, while the merge phrase is meant to fill parameters in the phrase text.

**Comment by EpicKris** [comment]
Good point, thanks.
